CREATE TABLE GENRE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE MOVIE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    description VARCHAR(60) DEFAULT NULL,
    genre_id BIGINT,
    CONSTRAINT FK_GENRE_ID FOREIGN KEY (genre_id) REFERENCES GENRE(id) ON DELETE SET NULL
);